// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhD8GUw5OcrT9MKZiUWlcNDyKJuT2k-TM',
    appId: '1:978603251493:web:2497e997ccd349849c6ccc',
    messagingSenderId: '978603251493',
    projectId: 'resculpt-23',
    authDomain: 'resculpt-23.firebaseapp.com',
    storageBucket: 'resculpt-23.appspot.com',
    measurementId: 'G-3XFMN49FYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLiFwvliRJwgCz4ObgbZMa2KNgwpVuRd4',
    appId: '1:978603251493:android:8eb4ecddce95888b9c6ccc',
    messagingSenderId: '978603251493',
    projectId: 'resculpt-23',
    storageBucket: 'resculpt-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1FgifyKtOGUCvKOQf2LJNMF_7YSb0SQ',
    appId: '1:978603251493:ios:481712a4c0df85cf9c6ccc',
    messagingSenderId: '978603251493',
    projectId: 'resculpt-23',
    storageBucket: 'resculpt-23.appspot.com',
    androidClientId: '978603251493-lcviob9mj694v8s3n33jprfpgtts5ctb.apps.googleusercontent.com',
    iosClientId: '978603251493-f2kd6akct0s7oefjom0toeeicbq0je21.apps.googleusercontent.com',
    iosBundleId: 'com.example.resculpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1FgifyKtOGUCvKOQf2LJNMF_7YSb0SQ',
    appId: '1:978603251493:ios:0f31fc0d13582cca9c6ccc',
    messagingSenderId: '978603251493',
    projectId: 'resculpt-23',
    storageBucket: 'resculpt-23.appspot.com',
    androidClientId: '978603251493-lcviob9mj694v8s3n33jprfpgtts5ctb.apps.googleusercontent.com',
    iosClientId: '978603251493-oful06oopm8rtuoaqo7e7fv3n2fcd2iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.resculpt.RunnerTests',
  );
}
